### Problemgroesen:

In [1]:
import numpy as np
objects = [(46,3),(84,5),(22,2),(32,2),(76,4),(35,2)]
capacity = 10

### Algorithmus (Matrix erstellen)

In [2]:
def dynamic_prog(objects, capacity):
    result = np.zeros((len(objects)+1,capacity+1)).astype(int)
    for i in range(len(objects)):
        for c in range(1,capacity+1):
            if objects[i][1] > c:
                result[i+1][c] = result[i][c]
            else:
                result[i+1][c]= max(result[i][c], result[i][c-objects[i][1]] + objects[i][0])
    print(result)
    return result


### Matrix auswerten

In [3]:
def solve(matrix, objects):
    result = set()
    I,J = matrix.shape
    I-= 1
    J-= 1
    while(I!=0 and J!=0):
        if matrix[I][J]==matrix[I-1][J]:
            matrix = matrix[:I]
            I -= 1
            continue
        if matrix[I][J] == matrix[I-1][J]:
            matrix = matrix[0:I+1][:J]
            J -= 1
            continue
        result.add(I-1)
        J -= objects[I-1][1]
        I -= 1
    return result

### Test

In [4]:
matrix = dynamic_prog(objects, capacity)

[[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  46  46  46  46  46  46  46  46]
 [  0   0   0  46  46  84  84  84 130 130 130]
 [  0   0  22  46  46  84  84 106 130 130 152]
 [  0   0  32  46  54  84  84 116 130 138 162]
 [  0   0  32  46  76  84 108 122 130 160 162]
 [  0   0  35  46  76  84 111 122 143 160 165]]


In [5]:
solve(matrix, objects)

6 10


{0, 1, 5}